-- Enable PostGIS if needed (optional for simple lat/lon, but good for future)
-- create extension if not exists postgis;

-- 1. Operational Tables
create table if not exists public.buses (
    bus_id text primary key,
    depot_id text not null,
    capacity int not null default 50,
    created_at timestamptz default now()
);

create table if not exists public.routes (
    route_id text primary key,
    city text not null,
    length_km float,
    created_at timestamptz default now()
);

create table if not exists public.stops (
    stop_id text primary key,
    lat float not null,
    lon float not null,
    route_id text references public.routes(route_id),
    name text,
    created_at timestamptz default now()
);

create table if not exists public.gps_logs (
    id bigint generated by default as identity primary key,
    bus_id text references public.buses(bus_id),
    timestamp timestamptz not null default now(),
    lat float not null,
    lon float not null,
    speed float
);

create table if not exists public.ticket_logs (
    id bigint generated by default as identity primary key,
    route_id text references public.routes(route_id),
    stop_id text references public.stops(stop_id),
    timestamp timestamptz not null default now(),
    count int default 1
);

-- 2. Analytics Tables
create table if not exists public.delay_predictions (
    id bigint generated by default as identity primary key,
    bus_id text references public.buses(bus_id),
    route_id text references public.routes(route_id),
    predicted_delay float, -- in minutes
    confidence float,
    timestamp timestamptz default now()
);

create table if not exists public.demand_forecasts (
    id bigint generated by default as identity primary key,
    route_id text references public.routes(route_id),
    time_slot timestamptz not null,
    predicted_demand int,
    created_at timestamptz default now()
);

create table if not exists public.route_utilization (
    id bigint generated by default as identity primary key,
    route_id text references public.routes(route_id),
    utilization_score float,
    created_at timestamptz default now()
);

-- 3. AI Decision Tables
create table if not exists public.ai_recommendations (
    rec_id uuid default gen_random_uuid() primary key,
    route_id text references public.routes(route_id),
    recommendation text not null,
    reason text,
    expected_impact text,
    confidence float,
    status text default 'pending', -- pending, accepted, rejected
    created_at timestamptz default now()
);

-- 4. Governance
create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id),
    action text not null,
    details jsonb,
    timestamp timestamptz default now()
);

create table if not exists public.planner_feedback (
    id bigint generated by default as identity primary key,
    rec_id uuid references public.ai_recommendations(rec_id),
    user_id uuid references auth.users(id),
    action text not null, -- accepted, rejected
    comment text,
    created_at timestamptz default now()
);

-- Realtime enablement
alter publication supabase_realtime add table public.gps_logs;
alter publication supabase_realtime add table public.delay_predictions;
alter publication supabase_realtime add table public.ai_recommendations;

-- RLS Policies (Basic)
alter table public.buses enable row level security;
alter table public.routes enable row level security;
alter table public.stops enable row level security;
alter table public.gps_logs enable row level security;
alter table public.ticket_logs enable row level security;
alter table public.delay_predictions enable row level security;
alter table public.demand_forecasts enable row level security;
alter table public.route_utilization enable row level security;
alter table public.ai_recommendations enable row level security;
alter table public.audit_logs enable row level security;
alter table public.planner_feedback enable row level security;

-- Allow read access to authenticated users
create policy "Allow read access for authenticated users" on public.buses for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.routes for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.stops for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.gps_logs for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.ticket_logs for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.delay_predictions for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.demand_forecasts for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.route_utilization for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.ai_recommendations for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.audit_logs for select using (auth.role() = 'authenticated');
create policy "Allow read access for authenticated users" on public.planner_feedback for select using (auth.role() = 'authenticated');

-- Allow insert/update for service role (backend) or specific roles (omitted for brevity, using simple authenticated for now for demo)
create policy "Allow all access for service role" on public.buses using (true) with check (true); 
-- In reality, we might restrict writes to service_role mostly.
